default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: scriptedbot_development

test:
  <<: *default
  database: scriptedbot_test

production:
  <<: *default
  database: scriptedbot_production
