school_name: <%= ENV['SCRIPTEDBOT_SCHOOL_NAME'] %>
links:
  daily_session_document: <%= ENV['SCRIPTEDBOT_DAILY_SESSION_LINK'] %>
  reference_table: "https://github.com/ScriptEdcurriculum/curriculum2016/blob/master/resources/ScriptEdReferenceTable2016.pdf"
attendance:
  class_days:
    tuesday:
      start_time: '08:50'
    wednesday:
      start_time: '08:50'
  lateness_threshold: 10
  absence_threshold: 30
