airbrake:
  project_id: <%= ENV['AIRBRAKE_PROJECT_ID'] %>
  project_key: <%= ENV['AIRBRAKE_API_KEY'] %>
school:
  name: <%= ENV['SCRIPTEDBOT_SCHOOL_NAME'] %>
  bot_pic: <%= ENV['SCRIPTEDBOT_PIC'] || 'greenschoolbot.jpg' %>
github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
links:
  daily_session_document: <%= ENV['SCRIPTEDBOT_DAILY_SESSION_LINK'] %>
  reference_table: "https://github.com/ScriptEdcurriculum/curriculum2016/blob/master/resources/ScriptEdReferenceTable2016.pdf"
attendance:
  class_days:
    tuesday:
      hour: 8
      minute: 50
    wednesday:
      hour: 8
      minute: 50
  lateness_threshold: 2
