time_zone: <%= ENV['SCRIPTED_BOT_TIME_ZONE'] || 'America/New_York' %>
airbrake:
  project_id: <%= ENV['AIRBRAKE_PROJECT_ID'] %>
  project_key: <%= ENV['AIRBRAKE_API_KEY'] %>
school:
  name: <%= ENV['SCRIPTEDBOT_SCHOOL_NAME'] %>
  bot_pic: <%= ENV['SCRIPTEDBOT_PIC'] || 'greenschoolbot.jpg' %>
github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
links:
  daily_session_document: <%= ENV['SCRIPTEDBOT_DAILY_SESSION_LINK'] %>
  reference_table: "https://github.com/ScriptEdcurriculum/curriculum2016/blob/master/resources/ScriptEdReferenceTable2016.pdf"
attendance:
  early_threshold: <%= ENV['SCRIPTED_BOT_EARLY_THRESHOLD'] || 45 %>
  late_threshold: <%= ENV['SCRIPTED_BOT_LATE_THRESHOLD'] || 5 %>
  class_days:
    tuesday:
      hour: 11
      minute: 0
    wednesday:
      hour: 8
      minute: 50
